name: Pipeline [test -> build -> deploy]
on:
  push:
    branches:
      - '**'
permissions:
  contents: read
  packages: write
concurrency:
  # only cancel in progress when on a branch - use SHA on main to ensure uniqueness
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  gradle_verify:
    name: Run the tests
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/gradle_verify.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
